apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kubernetes-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-kubernetes
          image: anastasijac/nginx-kubernetes:1.0
          ports:
            - containerPort: 80
